# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Visualization Hub
author: Group 11
description: >- # this means to ignore newlines until "baseurl:"
  A collection of interactive data stories and visualizations for SDA course.
baseurl: /SDA/ # the subpath of your site, e.g. /blog
domain: eszterkovacs17.github.io
url: https://eszterkovacs17.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

defaults:
  - scope:
      path: ""
    values:
      layout: "default"


# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-lunr-js-search
lunr_search:
  exclude: [index.md, about.md]  # Files to exclude from search
  search_path: ""  # Search across the whole site
  fulltext: true

#theme:  jekyll-theme-architect
#plugins:
#  - jekyll-feed

#Modify _config.yml to make sure Jekyll processes the custom styles:
sass:
  style: compressed
  load_paths:
    - _sass

#adding a sidebar
sidebar:
  nav: "main"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
